---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangke200377.
--- DateTime: 2023/7/31 上午9:19
---

local config = require("utils.config")

local routes = {}

for i,v in ipairs(config.get("URL_PATTERNS", {})) do
    routes[i] = {
        paths = { v.pattern },
        metadata = v,
    }
end

local radix = require("resty.radixtree")

local rad = radix.new(routes)

local _M = {}

function _M.route(path)
    local route = rad.match(path)
    if not route then
        return {
            auth = false,
            cache = false,
        }
    end

    return route
end

return _M